# Generated by Django 4.0 on 2022-01-29 11:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('phone', models.CharField(max_length=50, verbose_name='phone')),
                ('birthday', models.DateField(default=datetime.date.today, verbose_name='birthday')),
                ('email', models.CharField(max_length=254, verbose_name='email')),
                ('address', models.CharField(max_length=254, verbose_name='address')),
            ],
        ),
    ]
