# Generated by Django 4.0 on 2022-02-04 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('TECH', 'TECH'), ('SCIENCE', 'SCIENCE'), ('HEALTH', 'HEALTH'), ('SPORT', 'SPORT')], max_length=40)),
            ],
        ),
    ]
