version: "3"

services:
  db:
    image: mariadb
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=mypass
      - MYSQL_DATABASE=sys
      - MYSQL_USER=root
      - MYSQL_PASSWORD=mypass
    volumes:
      - mariadb_data:/var/lib/mysql
    ports:
      - "3306:3306"
  web:
    image: janga
    command: python personal_assistent_web/manage.py runserver 0.0.0.0:8000
    restart: always
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db

volumes:
  mariadb_data:
