# Generated by Django 4.0.1 on 2022-01-30 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noteapp', '0002_notes_pub_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes',
            name='tag',
            field=models.CharField(choices=[('annotation', 'annotation'), ('chronicle', 'chronicle'), ('opened information', 'opened information'), ('announcement', 'announcement'), ('private note', 'private note'), ('event note', 'event note'), ('business note', 'business note'), ('review', 'review'), ('mini story', 'mini story')], default='annotation', max_length=50),
        ),
    ]
